export const levelWiseSentences = ["dvasdvasdjnsdvoa ajndfjas dnlansdlnv ", " fsvsdfvsdvdsvsv"];
export const randomSentences =  [
    "The quick brown fox swiftly leapt over the lazy dog near the quiet village while curious children cautiously watched the clever creature disappear beyond the winding woodland path.",
    "Peter Piper picked a peck of pickled peppers, yet persistent practice proved painfully precise because proper pronunciation and rapid repetition require disciplined focus, steady rhythm, and deliberate control of every small finger movement.",
    "Engineers carefully examine complex mechanical systems because a tiny overlooked defect can silently trigger a catastrophic chain of failures that spreads through interconnected components and ultimately cripples the entire structure.",
    "Six slippery snails slowly slid southward across smooth stone steps during a sudden spring shower while several startled sparrows scattered swiftly through the soaked garden searching for shelter.",
    "Bright sparks spiraled spectacularly through the dim workshop as skilled blacksmiths steadily struck stubborn steel with heavy hammers, shaping resilient tools through patience, precision, and countless controlled repetitions.",
    "She sells seashells by the seashore, yet seasoned sailors still stumble slightly when swiftly repeating the sentence because subtle shifts of sound and rhythm easily confuse careless or hurried speakers.",
    "The disciplined developer deliberately designs dependable distributed systems because resilient software demands thoughtful architecture, careful concurrency control, and relentless testing against unpredictable network delays, corrupted packets, and unexpected user behavior.",
    "Swift swallows swooped silently across silver streams while sudden storms stirred swirling sheets of rain that swept across the valley and soaked the scattered farms beyond the distant hills.",
    "Focused fingers flow fluidly across familiar keyboard keys only when frequent practice transforms hesitant movements into confident automatic reflexes that maintain rhythm even while difficult punctuation and complex vocabulary appear unexpectedly.",
    "The restless reporter rapidly recorded remarkable revelations while relentless rain rattled loudly against the newsroom windows and thunder rolled repeatedly across the darkening skyline.",
    "Three thoughtful thinkers thoroughly tested their theoretical framework through tireless trials, careful measurements, and transparent discussion until the final conclusion finally withstood every skeptical question from experienced reviewers.",
    "Freshly fried fish filled the foggy harbor with a fragrant aroma while patient fishermen repaired fraying nets and quietly prepared their small boats for the uncertain journey beyond the gray horizon.",
    "Complex cryptographic calculations conceal confidential communication across insecure networks while clever attackers constantly attempt subtle strategies designed to exploit overlooked vulnerabilities within poorly implemented security systems.",
    "The patient pianist practiced peculiar passages repeatedly until precise performance replaced persistent painful mistakes and the complicated composition finally flowed smoothly beneath disciplined fingers.",
    "Powerful processors perform parallel computations precisely when carefully written programs distribute demanding workloads efficiently across multiple cores without introducing race conditions or unpredictable synchronization delays.",
    "Seven slick swords slid sharply from sturdy scabbards as seasoned soldiers silently surveyed the shadowed valley where suspicious movements hinted at a possible ambush hidden among the distant ridges.",
    "Accurate typing requires deliberate discipline because careless corrections compound costly cognitive interruptions that gradually destroy momentum and force frustrated users to repeatedly restart entire sections of text.",
    "The vigilant validator verified variable values vigorously because vague validation vulnerabilities invite vicious virtual attacks capable of compromising critical systems and exposing confidential data.",
    "Rapid rhythmic keystrokes reveal refined reflexes developed through relentless repetition, while random hesitation exposes fragile foundational habits that prevent consistent typing accuracy during stressful timed tests.",
    "Curious children cautiously crossed the creaking corridor because the ancient building contained countless concealed passages and unstable structures that threatened sudden collapse beneath careless footsteps.",
    "Persistent programmers patiently pursue perplexing problems until precise patterns emerge from confusing codebases, allowing them to transform tangled logic into reliable algorithms that perform predictably under demanding conditions.",
    "The stubborn storm steadily strengthened overnight, scattering ships across the restless sea and shattering silent seaside settlements with relentless waves that crashed violently against ancient stone walls.",
    "Professional pilots precisely position powerful aircraft during turbulent descents despite unpredictable pressure shifts, violent crosswinds, and the constant responsibility of protecting hundreds of passengers.",
    "Eight eager editors examined every error meticulously because even a minor grammatical mistake or misleading phrase might confuse millions of readers who depend upon clear and trustworthy reporting.",
    "Sharp scissors sliced silky satin smoothly while skilled seamstresses stitched spectacular ceremonial costumes designed to shimmer brilliantly beneath bright stage lights during the evening performance.",
    "Creative composers carefully construct complex chord progressions so subtle harmonic transitions sustain emotional resonance throughout an entire musical piece without overwhelming the listener with chaotic sound.",
    "Rapidly rising river waters rushed relentlessly past rocky ridges and ruined several rural roads before frightened residents finally evacuated their homes and retreated toward higher ground.",
    "Wise writers weigh every word thoughtfully because careless composition corrupts clear communication and transforms simple ideas into confusing paragraphs filled with unnecessary complexity.",
    "Daring divers descended deep beneath dark waters while distant dolphins danced gracefully through drifting currents and beams of sunlight filtered faintly through the shifting surface above.",
    "Seasoned security specialists simulate sophisticated cyberattacks against their own infrastructure to strengthen defensive systems and reveal subtle weaknesses before malicious actors can exploit them.",
    "Clever cats cautiously crept across cluttered cupboards chasing chirping crickets concealed inside cracked containers while the quiet kitchen echoed with the faint tapping of curious paws.",
    "Reliable robots rapidly retrieve requested resources from organized storage facilities while redundant systems constantly monitor performance and prevent dangerous failures during critical operations.",
    "The brisk winter wind blew bitterly across barren branches while birds battled bravely against the cold and scattered leaves skittered noisily along the empty pavement.",
    "Massive migrating monarch butterflies drift delicately across distant deserts despite dangerous winds and dwindling resting grounds scattered sparsely across the changing landscape.",
    "Dedicated data scientists scrutinize suspicious statistical signals carefully before broadcasting confident conclusions because misleading correlations often conceal deeper complexities hidden within messy datasets."
  ]

